test:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "jzfwccp-nf75387"
      user: "airbyte_user"
      password: "R1cSc4&cC1qmaUmY"
      role: "AIRBYTE_ROLE"
      warehouse: "PRODUCTS_WH"
      database: "CAROL_RAW"
      schema: "RAW"
      threads: 4
      client_session_keep_alive: False
      query_tag: dbt
      connect_retries: 0 # default 0
      connect_timeout: 3 # default: 10
